# Generated by Django 2.2.5 on 2020-05-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('d_o_b', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=30)),
                ('passwd', models.SlugField(max_length=400)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
